(deftheme ale-black-3
  "Created 2014-10-23.")

(custom-theme-set-variables
 'ale-black-3
 '(evil-default-cursor (quote (quote (t "#cc0044"))))
 '(scroll-bar-mode nil)
 '(visible-bell t)
 '(menu-bar-mode nil)
 '(show-paren-mode t)
 '(tool-bar-mode nil))

(custom-theme-set-faces
 'ale-black-3
 '(ac-candidate-face ((t (:background "light gray" :foreground "black" :underline "light slate blue"))))
 '(ac-clang-candidate-face ((t (:background "light gray" :foreground "navy" :underline "medium slate blue"))))
 '(diff-hl-change ((t (:background "slate blue" :foreground "blue3"))))
 '(diff-removed ((t (:inherit diff-changed :background "firebrick4"))))
 '(ediff-odd-diff-C ((t (:background "dim grey" :foreground "White"))))
 '(eldoc-highlight-function-argument ((t (:inherit bold :box nil :underline "deep pink"))))
 '(factor-font-lock-comment ((t (:inherit font-lock-comment-face))))
 '(factor-font-lock-parsing-word ((t (:inherit font-lock-keyword-face))))
 '(factor-font-lock-stack-effect ((t (:foreground "green"))))
 '(factor-font-lock-string ((t (:inherit font-lock-string-face))))
 '(factor-font-lock-word ((t (:inherit font-lock-function-name-face))))
 '(flx-highlight-face ((t (:inherit font-lock-keyword-face :underline t :weight bold))))
 '(flycheck-error ((t (:inherit error :underline t))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "MediumPurple2"))))
 '(font-lock-comment-face ((t (:foreground "MediumPurple3" :slant italic))))
 '(font-lock-fic-face ((((class color)) (:background "Red" :foreground "Yellow" :weight bold))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face :foreground "yellow"))))
 '(font-lock-string-face ((t (:foreground "blue violet"))))
 '(font-lock-warning-face ((t (:inherit error :foreground "goldenrod"))))
 '(highlight-indentation-face ((t (:inherit fringe :background "grey8"))))
 '(hl-sexp-face ((t (:background "gray7"))))
 '(jedi:highlight-function-argument ((t (:inherit eldoc-highlight-function-argument))))
 '(magit-log-author ((t (:foreground "MediumPurple1"))))
 '(magit-log-sha1 ((t (:foreground "cornflower blue"))))
 '(mode-line ((t (:background "grey" :foreground "black" :height 100 :family "Consolas"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :weight light))))
 '(popup-scroll-bar-foreground-face ((t (:background "blue"))))
 '(powerline-enotify-bg-face ((t (:background "gray8" :foreground "grey75" :box (:line-width 1 :color "grey75" :style released-button) :slant italic :weight bold))))
 '(pp^L-highlight ((t (:background "#120c14" :foreground "black"))))
 '(region ((t (:background "#382D7B"))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 80 :width normal))))
 '(bold ((t (:weight bold))))
 '(cursor ((t (:background "#cc00cc"))))
 '(erc-keyword-face ((t (:foreground "magenta" :weight bold))))
 '(error ((t (:foreground "Red" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "medium slate blue"))))
 '(font-lock-constant-face ((t (:foreground "#ff0022"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "purple3"))))
 '(font-lock-function-name-face ((t (:foreground "deeppink" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "dodger blue" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "dark slate grey"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "steel blue"))))
 '(font-lock-type-face ((t (:foreground "spring green" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "forest green" :weight bold))))
 '(ido-first-match ((t (:slant italic :weight bold))))
 '(ido-subdir ((t (:foreground "dodger blue"))))
 '(info-header-node ((t (:inherit info-node :foreground "gold"))))
 '(info-header-xref ((t (:inherit info-xref :foreground "yellow"))))
 '(info-menu-header ((t (:inherit variable-pitch :foreground "DodgerBlue1" :weight bold :height 1.5))))
 '(info-node ((t (:foreground "yellow" :slant italic :weight bold))))
 '(info-title-4 ((t (:inherit variable-pitch :foreground "dark violet" :weight bold))))
 '(info-xref-visited ((t (:inherit (link-visited info-xref)))))
 '(link ((t (:foreground "DodgerBlue3" :underline t))))
 '(link-visited ((t (:inherit link :foreground "purple3"))))
 '(menu ((t (:foreground "red" :height 80))))
 '(minibuffer-prompt ((t (:foreground "LimeGreen"))))
 '(mode-line-buffer-id ((t (:slant italic :weight bold :height 0.9 :family "Segoe UI"))))
 '(paren-face ((t (:foreground "dim gray"))))
 '(show-paren-mismatch ((t (:background "white" :foreground "red"))))
 '(trailing-whitespace ((t (:background "grey50"))))
 '(woman-bold ((t (:inherit bold :foreground "deep sky blue")))))

(provide-theme 'ale-black-3)
