(deftheme ale-black-2
  "Created 2013-02-24.")

(custom-theme-set-variables
 'ale-black-2
 '(Info-additional-directory-list (quote ("/home/ale/Dropbox/emacs/info")))
 '(custom-safe-themes (quote ("7f96e6a6dd9b02aeae63cde2916f2725eaf91b44049cdc9cf608ceff4c2a3732" "937192841e98d0260e5d2f24c5937136ea2ef5b9f5dcf79937a927da7fd07d9a" "c10c5633b72da0ab27ef6078173e950c770feee9ec755a4ef4b54b711647b637" "6ce86d5929771a629df54a073ad652a480be17cd7f75b76a61ad7be84b3766c8" default)))
 '(diff-switches "-u")
 '(erc-beep-match-types (quote (current-nick keyword)))
 '(erc-keywords (quote ("enotify" "evil")))
 '(evil-default-cursor (quote (t "#CC00CC")))
 '(evil-emacs-state-modes (quote (eassist-mode archive-mode bbdb-mode bookmark-bmenu-mode bookmark-edit-annotation-mode browse-kill-ring-mode bzr-annotate-mode calc-mode cfw:calendar-mode completion-list-mode Custom-mode debugger-mode delicious-search-mode desktop-menu-blist-mode desktop-menu-mode doc-view-mode dvc-bookmarks-mode dvc-diff-mode dvc-info-buffer-mode dvc-log-buffer-mode dvc-revlist-mode dvc-revlog-mode dvc-status-mode dvc-tips-mode ediff-mode efs-mode Electric-buffer-menu-mode emms-browser-mode emms-mark-mode emms-metaplaylist-mode emms-playlist-mode ert-results-mode etags-select-mode fj-mode gc-issues-mode gdb-breakpoints-mode gdb-disassembly-mode gdb-frames-mode gdb-locals-mode gdb-memory-mode gdb-registers-mode gdb-threads-mode gist-list-mode gnus-article-mode gnus-browse-mode gnus-group-mode gnus-server-mode gnus-summary-mode google-maps-static-mode ibuffer-mode jde-javadoc-checker-report-mode magit-commit-mode magit-diff-mode magit-key-mode magit-log-mode magit-mode magit-reflog-mode magit-show-branches-mode magit-stash-mode magit-status-mode magit-wazzup-mode mh-folder-mode monky-mode notmuch-hello-mode notmuch-search-mode notmuch-show-mode occur-mode org-agenda-mode package-menu-mode proced-mode rcirc-mode rebase-mode recentf-dialog-mode reftex-select-bib-mode reftex-toc-mode sldb-mode slime-inspector-mode slime-thread-control-mode slime-xref-mode sr-buttons-mode sr-mode sr-tree-mode sr-virtual-mode tar-mode tetris-mode tla-annotate-mode tla-archive-list-mode tla-bconfig-mode tla-bookmarks-mode tla-branch-list-mode tla-browse-mode tla-category-list-mode tla-changelog-mode tla-follow-symlinks-mode tla-inventory-file-mode tla-inventory-mode tla-lint-mode tla-logs-mode tla-revision-list-mode tla-revlog-mode tla-tree-lint-mode tla-version-list-mode twittering-mode urlview-mode vc-annotate-mode vc-dir-mode vc-git-log-view-mode vc-svn-log-view-mode vm-mode vm-summary-mode w3m-mode wab-compilation-mode xgit-annotate-mode xgit-changelog-mode xgit-diff-mode xgit-revlog-mode xhg-annotate-mode xhg-log-mode xhg-mode xhg-mq-mode xhg-mq-sub-mode xhg-status-extra-mode eclim-project-mode eclim-problems-mode)))
 '(evil-want-C-w-in-emacs-state t)
 '(indent-tabs-mode nil)
 '(indicate-empty-lines t)
 '(inhibit-startup-screen nil)
 '(initial-buffer-choice t)
 '(semantic-default-submodes (quote (global-semantic-highlight-func-mode global-semantic-stickyfunc-mode global-semantic-idle-scheduler-mode global-semanticdb-minor-mode global-semantic-show-unmatched-syntax-mode)))
 '(send-mail-function (quote smtpmail-send-it))
 '(user-full-name "Alessandro Piras")
 '(user-mail-address "laynor@gmail.com")
 '(show-paren-mode t))

(custom-theme-set-faces
 'ale-black-2
 '(bold ((t (:weight bold))))
 '(bow ((t (:inherit nil :background "gray80" :foreground "black"))))
 '(cursor ((t (:background "#CC00CC"))))
 '(eldoc-highlight-function-argument ((t (:inherit bold :box (:line-width 2 :color "magenta1" :style released-button)))))
 '(erc-keyword-face ((t (:foreground "magenta" :weight bold))))
 '(error ((t (:foreground "Red" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "medium slate blue"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "MediumPurple2"))))
 '(font-lock-comment-face ((t (:foreground "MediumPurple3"))))
 '(font-lock-constant-face ((t (:foreground "#ff0022"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "purple3"))))
 '(font-lock-fic-face ((((class color)) (:background "Red" :foreground "Yellow" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "deeppink" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "dodger blue" :weight bold))))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face :foreground "yellow"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "dark slate grey"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "steel blue"))))
 '(font-lock-type-face ((t (:foreground "spring green" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "forest green" :weight bold))))
 '(geiser-font-lock-autodoc-current-arg ((t (:background "dim gray" :weight bold))))
 '(hl-line ((t (:background "grey13"))))
 '(hri-macros-face ((t (:foreground "dark slate blue"))))
 '(ido-first-match ((t (:slant italic :weight bold))))
 '(ido-subdir ((t (:foreground "Dodgerblue"))))
 '(info-header-node ((t (:inherit info-node :foreground "gold"))))
 '(info-header-xref ((t (:inherit info-xref :foreground "yellow"))))
 '(info-menu-header ((t (:inherit variable-pitch :foreground "DodgerBlue1" :weight bold :height 1.5))))
 '(info-node ((t (:foreground "yellow" :slant italic :weight bold))))
 '(info-title-4 ((t (:inherit variable-pitch :foreground "dark violet" :weight bold))))
 '(info-xref-visited ((t (:inherit (link-visited info-xref)))))
 '(link ((t (:foreground "DodgerBlue3" :underline t))))
 '(link-visited ((t (:inherit link :foreground "purple3"))))
 '(menu ((t (:foreground "red" :height 80))))
 '(minibuffer-prompt ((t (:foreground "LimeGreen"))))
 '(mode-line-buffer-id ((t (:slant italic :weight bold :height 0.9 :family "Segoe UI"))))
 '(paren-face ((t (:foreground "dim gray"))))
 '(pp^L-highlight ((t (:foreground "#440044" :box (:line-width 1 :style pressed-button)))))
 '(show-paren-mismatch ((t (:background "white" :foreground "red"))))
 '(slime-repl-inputed-output-face ((t (:foreground "maroon1"))))
 '(trailing-whitespace ((t (:background "grey50"))))
 '(w3m-anchor ((t (:inherit link :foreground "red"))))
 '(w3m-arrived-anchor ((t (:inherit link :foreground "magenta"))))
 '(w3m-current-anchor ((t (:underline t :weight bold))))
 '(w3m-header-line-location-title ((t (:background "Gray15" :foreground "dodger blue"))))
 '(w3m-image ((t (:inherit black-on-white))))
 '(woman-bold ((t (:inherit bold :foreground "deep sky blue"))))
 '(flymake-errline ((((class color)) (:underline "red"))))
 '(flymake-warnline ((((class color)) (:underline "yellow"))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 80 :width normal :family "terminus")))))

(provide-theme 'ale-black-2)
