.DEFAULT_GOAL := upload
# Board type: 1p, 2p, 1, 2, etc.
TEENSY = 2p
# Path to your teensyduino/arduino installation
ARDUINO_Linux = $(HOME)/src/teensy/arduino/arduino-1.0.5/
include teensyduino.mk
Makefile:;
