.DEFAULT_GOAL := upload
# Board type: 1p, 2p, 1, 2, etc.
# TEENSY = $[board-type]
# Path to your teensyduino/arduino installation
# ARDUINO_Linux = $[teensyduino-install-dir]
include teensyduino.mk
Makefile:;
